server:
  port: 8000

url:
  frontend: http://localhost:4200
  backend: http://localhost:8000

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ImageEffectsLogs
#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/springgdb
